//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 
using System.Xml.Serialization;


/// <remarks/>
[System.Xml.Serialization.XmlRootAttribute("detection-run", Namespace="", IsNullable=false)]
public class detectionrun {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("wireless-network")]
    public detectionrunWirelessnetwork[] wirelessnetwork;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("kismet-version")]
    public string kismetversion;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("start-time")]
    public string starttime;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("end-time")]
    public string endtime;
}

/// <remarks/>
public class detectionrunWirelessnetwork {
    
    /// <remarks/>
    public string SSID;
    
    /// <remarks/>
    public string BSSID;
    
    /// <remarks/>
    public string info;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool infoSpecified;
    
    /// <remarks/>
    public System.Decimal channel;
    
    /// <remarks/>
    public System.Decimal maxrate;
    
    /// <remarks/>
    public string maxseenrate;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("encryption")]
    public string encryption;
    
    /// <remarks/>
    public detectionrunWirelessnetworkPackets packets;
    
    /// <remarks/>
    public string datasize;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("gps-info")]
    public detectionrunWirelessnetworkGpsinfo gpsinfo;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ip-address")]
    public detectionrunWirelessnetworkIpaddress ipaddress;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("wireless-client")]
    public detectionrunWirelessnetworkWirelessclient[] wirelessclient;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string number;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string wep;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cloaked;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("first-time")]
    public string firsttime;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("last-time")]
    public string lasttime;
}

/// <remarks/>

/// <remarks/>

/// <remarks/>

/// <remarks/>
public class detectionrunWirelessnetworkPackets {
    
    /// <remarks/>
    public System.Decimal LLC;
    
    /// <remarks/>
    public System.Decimal  data;
    
    /// <remarks/>
    public System.Decimal  crypt;
    
    /// <remarks/>
    public System.Decimal  weak;
    
    /// <remarks/>
    public System.Decimal  dupeiv;
    
    /// <remarks/>
    public System.Decimal  total;
}

/// <remarks/>

/// <remarks/>
public class detectionrunWirelessnetworkWirelessclientClientgpsinfo {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("client-min-lat")]
    public System.Decimal clientminlat;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("client-min-lon")]
    public System.Decimal clientminlon;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("client-min-alt")]
    public System.Decimal clientminalt;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("client-min-spd")]
    public System.Decimal clientminspd;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("client-max-lat")]
    public System.Decimal clientmaxlat;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("client-max-lon")]
    public System.Decimal clientmaxlon;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("client-max-alt")]
    public System.Decimal clientmaxalt;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("client-max-spd")]
    public string clientmaxspd;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit;
}

/// <remarks/>
public class detectionrunWirelessnetworkWirelessclientClientpackets {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("client-data")]
    public int clientdata;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("client-crypt")]
    public int clientcrypt;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("client-weak")]
    public int clientweak;
}

/// <remarks/>
public class detectionrunWirelessnetworkWirelessclient {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("client-mac")]
    public string clientmac;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("client-packets")]
    public detectionrunWirelessnetworkWirelessclientClientpackets clientpackets;
    
    /// <remarks/>
    [XmlElementAttribute("client-encryption")]
    public string clientencryption;
    
    /// <remarks/>
    [XmlElementAttribute("client-gps-info")]
    public detectionrunWirelessnetworkWirelessclientClientgpsinfo clientgpsinfo;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("client-datasize")]
    public int clientdatasize;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("client-maxrate")]
    public string clientmaxrate;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("client-maxseenrate")]
    public string clientmaxseenrate;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("client-ip-address")]
    public string clientipaddress;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string number;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool wep;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("first-time")]
    public string firsttime;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("last-time")]
    public string lasttime;
}

/// <remarks/>

/// <remarks/>

/// <remarks/>
/// <remarks/>
public class detectionrunWirelessnetworkIpaddress {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ip-range")]
    public string iprange;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public detectionrunWirelessnetworkIpaddressType type;
}

/// <remarks/>

/// <remarks/>
public enum detectionrunWirelessnetworkIpaddressType {
    
    /// <remarks/>
    arp,
    
    /// <remarks/>
    tcp,
    
    /// <remarks/>
    udp,
    dhcp
}

/// <remarks/>
public class detectionrunWirelessnetworkGpsinfo {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("min-lat")]
    public System.Decimal minlat;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("min-lon")]
    public System.Decimal minlon;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("min-alt")]
    public System.Decimal minalt;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("min-spd")]
    public System.Decimal minspd;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("max-lat")]
    public System.Decimal maxlat;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("max-lon")]
    public System.Decimal maxlon;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("max-alt")]
    public System.Decimal maxalt;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("max-spd")]
    public System.Decimal maxspd;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit;
}

/// <remarks/>

/// <remarks/>

/// <remarks/>

/// <remarks/>
